#!/sdf/sys/pkg6_amd64/bin/bash

echo "-------------------------------------------------------------------------------"
echo "                                 Phlog Stream"
echo "-------------------------------------------------------------------------------"
echo ""
echo ""

FILES="/ftp/pub/users/tomasino/phlog/*"

for f in $(ls -1t $FILES); do
  if [[ $f != *"gophermap"* ]]; then
    cat $f
    echo -e "\n\n\n"
  fi
done
